jobs:
  build:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate config file
        run: |
          echo "window.APP_CONFIG = {
            app_id: '${{ vars.APP_ID }}'
          };" > config.js  # Изменено: public/config.js → config.js
      
      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4
